services:
    home-app-frontend-dev:
        build:
            context: ../../../../
            dockerfile: apps/frontend/docker/development/Dockerfile
            args:
                - GIT_BRANCH
                - GIT_COMMIT
        image: home-app-frontend-development
