services:
  reverse-proxy:
    image: traefik:2.10
    container_name: homeapp-reverse-proxy
    restart: always
    networks:
      - proxy_network
    ports:
      - '80:80'
      - '443:443'
    volumes:
    - ./traefik:/etc/traefik
    - ./logs:/var/log/traefik
    # So that Traefik can listen to the Docker events
    - /var/run/docker.sock:/var/run/docker.sock:ro

networks: 
  proxy_network:
    external: true
    