#https://medium.com/refinitiv-developer-community/how-to-test-rest-api-with-visual-studio-code-rest-client-extensions-9f2e061d0299

### System routes
GET https://localhost:8070/api/v1/system/info

### Utils routes
GET https://localhost:8070/api/v1/utils/transactionCategories
###
GET https://localhost:8070/api/v1/utils/taxCategories
###
GET https://localhost:8070/api/v1/utils/paymentMethods
###
GET https://localhost:8070/api/v1/utils/bankAccounts
###
GET https://localhost:8070/api/v1/utils/tags
###
GET https://localhost:8070/api/v1/utils/constants/transactions

### Transactions routes
### Batch get
GET https://localhost:8070/api/v1/transactions
###
GET https://localhost:8070/api/v1/transactions?context=home&limit=5

### Get by id
GET https://localhost:8070/api/v1/transactions/1

### Get transaction origins
GET https://localhost:8070/api/v1/transactions/origins

### Post
POST https://localhost:8070/api/v1/transactions
Content-Type: multipart/form-data;boundary=~~~123

--~~~123
Content-Disposition: form-data; name="transaction" 

{
        "type": "expense",
        "context": "home",
        "category": "FOOD",
        "origin": "Grocery store",
        "description": "Some tasty food",
        "amount": -45.67,
        "date": {
            "datetime":"2023-06-14T11:38:00.000Z"
        },
        "paymentMethod": "EC",
        "sourceBankAccount": "HOME_ACCOUNT",
        "tags": ["Test", "Tag"],
        "agent": "Testbot"
}
--~~~123--

### Post to provoke error
POST https://localhost:8070/api/v1/transactions
Content-Type: application/json

{
    "test": "hello"
}

### Get transaction receipt
GET https://localhost:8070/api/v1/transactions/receipt/1

### Investments routes
GET https://localhost:8070/api/v1/investments