version: '3.6'
services:
    database:
        image: postgres:${PGIMAGE}
        restart: always
        command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
        environment:
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${PGPASSWORD}
            - POSTGRES_DB=${PGDATABASE}
            - PGDATA=/var/lib/postgresql/data
        container_name: '${PGCONTAINER_NAME}'
        ports:
            - '${PGPORT}:5432'
        # Works on Linux. Emulated on Windows?
        tmpfs: /var/lib/postgresql/data
        # Alternative solution
        # volumes:
        #     - ./pgdata:/var/lib/postgresql/data
