http:
  routers:
    home-app-over-https:
      entryPoints: ["http", "https"]
      middlewares: ["force-https"]
      # rule: "HostRegexp(`{any:.+}`)"
      rule: "Host (`<home-app-domain-name>`)"
      service: "home-app"
      tls:
        certResolver: "lets-encrypt"

  middlewares:
    force-https:
      redirectScheme:
        scheme: "https"

  services:
    home-app:
      loadBalancer:
        servers:
          - url: "http://<private-ip-server-1>:<private-port-server-1>/"
          - url: "http://<private-ip-server-2>:<private-port-server-2>/"
