version: '3.6'
services:
    database:
        image: postgres:${POSTGRES_IMAGE_TAG}
        command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        container_name: '${POSTGRES_CONTAINER_NAME}'
        ports:
            - '${POSTGRES_CONTAINER_PORT}:5432'
        tmpfs: /var/lib/postgresql/data
