services:
    home-app-frontend-production:
        build:
            context: ../../../../
            dockerfile: apps/frontend/docker/production/Dockerfile
            args:
                - GIT_BRANCH
                - GIT_COMMIT
        image: dsevkovych/home-app-frontend-production
